---
- name: run docker, docker-compose
  hosts: all
  become: yes
  
  tasks:

  - name: Check and print linux dist
    debug: var=ansible_os_family

  - block: # UBUNTU block
    - name: UB Git clone
      git:
        repo: https://github.com/Tealdris/webnotes.git
        dest: /home/ubuntu/webnotes/
        clone: yes
        update: yes

    - name: UB deploy Docker Compose stack
      command: docker stack deploy --compose-file /home/ubuntu/webnotes/docker-compose.yml ls3

    when: ansible_os_family == "Debian"

  - block: # RH block
    - name: RH Git clone
      git:
        repo: https://github.com/Tealdris/webnotes.git
        dest: /home/ec2-user/webnotes/
        clone: yes
        update: yes

    when: ansible_os_family == "RedHat"


...